/*
 * created by firman (1302100093)
 * berikan kritik dan saran di 085299911170
 * 
 * /

/*
 * input_mata_kuliah.java
 *
 * Created on May 17, 2012, 12:55:12 PM
 */
package data_mahasiswa;

import java.awt.Canvas;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URL;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

import koneksi.ClassDB;
import com.mysql.jdbc.PreparedStatement;
import com.sun.org.apache.bcel.internal.util.JavaWrapper;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author firnan
 */
public class input_mata_kuliah extends javax.swing.JFrame {

    private DefaultTableModel model;
    /** Creates new form input_mata_kuliah */
    public input_mata_kuliah() {
        initComponents();
           model=new DefaultTableModel();
        tblmaha.setModel(model);
        model.addColumn("Kode Mata Kuliah");
        model.addColumn("Mata Kuliah");
        model.addColumn("Kredit (K)");
        model.addColumn("Semester");
        
        btambah.setEnabled(true);
        bedit.setEnabled(true);
        bkeluar.setEnabled(true);
        bsimpan.setEnabled(false);
        bupdate.setEnabled(false);
        bhapus.setEnabled(true);
        jComboBox1.setEnabled(false);
        tkode.setEnabled(false);
        tnamamt.setEnabled(false);
        tk.setEnabled(false);
             loadData();
             bersih();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblmaha = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tkode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tnamamt = new javax.swing.JTextField();
        tk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        btambah = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bsimpan = new javax.swing.JButton();
        bupdate = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        bkeluar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tblmaha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblmaha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmahaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblmaha);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Kredit (K)");

        jLabel1.setText("Kode Mata kuliah");

        jLabel2.setText("Nama Matakuliah ");

        tnamamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamamtActionPerformed(evt);
            }
        });

        jLabel4.setText("Semester");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--pilih--", "Semester 1", "Semester 2", "Semester 3", "Semester 4", "Semester 5", "Semester 6", "Semester 7", "Semester 8", "Mata Kuliah Pilihan" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(21, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addGap(31, 31, 31)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tnamamt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tkode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(tkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tnamamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(tk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(45, Short.MAX_VALUE)))
        );

        btambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Add-32.png"))); // NOI18N
        btambah.setText("Baru");
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });

        bedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Edit-32.png"))); // NOI18N
        bedit.setText("Edit");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });

        bhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Delete-32.png"))); // NOI18N
        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bupdate.setText("Update");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });

        bkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/door_out.png"))); // NOI18N
        bkeluar.setText("Keluar");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        bkeluar1.setText("Batal");
        bkeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bhapus, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(btambah, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(bupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bedit, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(bsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(bkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                    .addComponent(bkeluar1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btambah)
                            .addComponent(bedit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bhapus)
                            .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bkeluar))
                        .addGap(18, 18, 18)))
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bkeluar1)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void tnamamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamamtActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tnamamtActionPerformed

private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        btambah.setEnabled(false);
        bedit.setEnabled(false);
        bhapus.setEnabled(false);
        bsimpan.setEnabled(true);
        bupdate.setEnabled(false);
        tblmaha.setVisible(false);
        tkode.setEnabled(true);
        tnamamt.setEnabled(true);
        tk.setEnabled(true);
        jComboBox1.setEnabled(true); 
        bersih();
    // TODO add your handling code here:
}//GEN-LAST:event_btambahActionPerformed

private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
     btambah.setEnabled(false);
        bedit.setEnabled(false);
        bhapus.setEnabled(false);
        bsimpan.setEnabled(false);
        bupdate.setEnabled(true);
        tblmaha.setVisible(false);
        tkode.setEnabled(true);
        tnamamt.setEnabled(true);
        tk.setEnabled(true);
        jComboBox1.setEnabled(true);
       
    // TODO add your handling code here:
}//GEN-LAST:event_beditActionPerformed

private void bkeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluar1ActionPerformed
 btambah.setEnabled(true);
        bedit.setEnabled(true);
        bkeluar.setEnabled(true);
        bsimpan.setEnabled(false);
        bupdate.setEnabled(false);
        bhapus.setEnabled(true);
        tblmaha.setVisible(true);
        tkode.setEnabled(false);
        tnamamt.setEnabled(false);
        tk.setEnabled(false);
        bersih();
        jComboBox1.setEnabled(false);// TODO add your handling code here:
}//GEN-LAST:event_bkeluar1ActionPerformed

private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
 this.dispose();// TODO add your handling code here:
}//GEN-LAST:event_bkeluarActionPerformed

private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
    TambahData();    
    bedit.setEnabled(true);
        bkeluar.setEnabled(true);
        bsimpan.setEnabled(false);
        bupdate.setEnabled(false);
        bhapus.setEnabled(true);
        btambah.setEnabled(true);
        jComboBox1.setEnabled(false);
        tkode.setEnabled(false);
        tnamamt.setEnabled(false);
        tk.setEnabled(false);
        loadData();
        JOptionPane.showMessageDialog(null, "Data telah tersimpan !!!");
         tblmaha.setVisible(true);
         bersih();
    // TODO add your handling code here:
}//GEN-LAST:event_bsimpanActionPerformed

private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
    UpdateData();    
    bedit.setEnabled(true);
        bkeluar.setEnabled(true);
        bsimpan.setEnabled(false);
        bupdate.setEnabled(false);
        bhapus.setEnabled(true);
        btambah.setEnabled(true);
        tkode.setEnabled(false);
        tnamamt.setEnabled(false);
         jComboBox1.setEnabled(false);
        tk.setEnabled(false);
        tblmaha.setVisible(true);
        JOptionPane.showMessageDialog(null, "Data telah tetupdate !!!");
        loadData();
        bersih();
         // TODO add your handling code here:
}//GEN-LAST:event_bupdateActionPerformed

private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
 String kode=this.tkode.getText();
        if ("".equals(kode.trim()) || kode.trim()==null)
          {
          return;
          }else{
        DeleteData();
        }// TODO add your handling code here:
}//GEN-LAST:event_bhapusActionPerformed

private void tblmahaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmahaMouseClicked
ShowData();// TODO add your handling code here:
}//GEN-LAST:event_tblmahaMouseClicked
public void bersih(){
    tk.setText("");
    tnamamt.setText("");
 tkode.setText("");
 jComboBox1.setSelectedIndex(0);
 
}
        
public void loadData() {
    
        String id = tkode.getText();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {            
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select * from dnilai";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                Object[] o=new Object[12];
                o[0]=r.getString("kode_mata_kuliah");
                o[1]=r.getString("nama_mata_kuliah");
                o[2]=r.getString("kredit");  
                o[3]=r.getString("Semester");  
                model.addRow(o);
            }
            r.close();
            s.close();
            
       
            ShowData();
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan");
        }
    }

public void TambahData() {
  String kode_mata_kuliah= this.tkode.getText();
  String nama_mata_kuliah=this.tnamamt.getText();
  String kredit=this.tk.getText();
  String semester=(String) this.jComboBox1.getSelectedItem();
       try {
           
            Connection c=ClassDB.getkoneksi();
            String sql = "Insert into dnilai values (?,?,?,?)";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kode_mata_kuliah);
            p.setString(2, nama_mata_kuliah);
            p.setString(3, kredit);
            p.setString(4, semester);           
            p.executeUpdate();
            p.close();
       
       }catch(SQLException e){
            System.out.println(e);
        }finally{
            loadData();
        }
}

public void UpdateData() {
    
    int i=tblmaha.getSelectedRow();
        if(i==-1)
        {
            return;
        }
  String id=(String) model.getValueAt(i, 0);
  String nama_mata_kuliah=this.tnamamt.getText();
  String kredit=this.tk.getText();
  String semester=(String) this.jComboBox1.getSelectedItem(); 
        try {
            Connection c=ClassDB.getkoneksi();
            String sql = "Update dnilai Set nama_mata_kuliah=?,kredit=?,semester=? WHERE kode_mata_kuliah=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, nama_mata_kuliah);
            p.setString(2, kredit);
             p.setString(3, semester);
            p.setString(4, id);
            p.executeUpdate();
            p.close();
             
        }catch(SQLException e){
            System.out.println("Terjadi kesalahan pada pengupdetan data");
        }finally{
            loadData();
        
            
}
}
public void DeleteData() {
    
    int i=tblmaha.getSelectedRow();
        if(i==-1)
        {
            return;
        }
        String id=(String) model.getValueAt(i, 0);
       
       
        try {
            Connection c=ClassDB.getkoneksi();
            String sql = "DELETE From dnilai  WHERE kode_mata_kuliah=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, id);            
            p.executeUpdate();
            p.close();
         }catch(SQLException e){
            System.out.println("Terjadi kesalahan");
        }finally{
            loadData();
        }
}
    
public void ShowData() {
     String id = tkode.getText();
       
    int i=tblmaha.getSelectedRow();
        
        if(i==-1)
        {
            return;
        }
        
  String kode_mata_kuliah=(String) model.getValueAt(i, 0);
  tkode.setText(kode_mata_kuliah);
  String nama_mata_kuliah=(String) model.getValueAt(i, 1);
  tnamamt.setText(nama_mata_kuliah);
  String kredit=(String) model.getValueAt(i, 2);
  tk.setText(kredit);
          
     }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(input_mata_kuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(input_mata_kuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(input_mata_kuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input_mata_kuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new input_mata_kuliah().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bedit;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bkeluar1;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton btambah;
    private javax.swing.JButton bupdate;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblmaha;
    private javax.swing.JTextField tk;
    private javax.swing.JTextField tkode;
    private javax.swing.JTextField tnamamt;
    // End of variables declaration//GEN-END:variables
}
